In [3]:
import os
import pandas as pd

In [5]:
CREMA_D_BASE_DIR = "audio_speech/CREMA_D"

In [1]:
error_files = [
    '1076_MTI_NEU_XX.wav', # very short, no audio
    '1076_MTI_SAD_XX.wav', # no audio, very short
    '1064_TIE_SAD_XX.wav', # file has no duration
    '1064_IEO_DIS_MD.wav' # this file is actually 1 minute long and has all emotional displays for It's Eleven O'clock.
    ]

In [6]:
crema_directory_list = os.listdir(CREMA_D_BASE_DIR)

file_emotion = []
file_path = []

for file in crema_directory_list:
    # skip file if is in error list
    if file in error_files:
        continue

    # Get path of each audio file
    file_path.append(CREMA_D_BASE_DIR + '/' + file)

    # Extract emotion
    emotion = file.split('_')[2] # split returns e.g. ['1001', 'DFA', 'ANG', 'XX.mp3'], emotion is in pos 2

    # To match the ravdess encodings
    if emotion == 'SAD':
        file_emotion.append(3)
    elif emotion == 'ANG':
        file_emotion.append(4)
    elif emotion == 'DIS':
        file_emotion.append(6)
    elif emotion == 'FEA':
        file_emotion.append(5)
    elif emotion == 'HAP':
        file_emotion.append(2)
    elif emotion == 'NEU':
        file_emotion.append(1)
    else:
        file_emotion.append(0)

In [7]:
df = pd.DataFrame(list(zip(file_path, file_emotion)), columns=['file_path', 'Emotion'])
df.head()

                                  file_path  Emotion
0  audio_speech/CREMA_D/1001_DFA_ANG_XX.wav        4
1  audio_speech/CREMA_D/1001_DFA_DIS_XX.wav        6
2  audio_speech/CREMA_D/1001_DFA_FEA_XX.wav        5
3  audio_speech/CREMA_D/1001_DFA_HAP_XX.wav        2
4  audio_speech/CREMA_D/1001_DFA_NEU_XX.wav        1

In [8]:
# Add human readable labels to the emotions
emotion_map = {
    1: "neutral",
    2: "happy",
    3: "sad",
    4: "angry",
    5: "fearful",
    6: "disgust",
    7: "surprised"
}

df["Emotion_label"] = df["Emotion"].map(emotion_map)

In [12]:
df.Emotion_label.value_counts().sort_index()

Emotion_label
angry      1096
disgust    1095
fearful    1096
happy      1096
neutral     934
sad        1093
Name: count, dtype: int64

In [10]:
df.head()

                                  file_path  Emotion Emotion_label
0  audio_speech/CREMA_D/1001_DFA_ANG_XX.wav        4         angry
1  audio_speech/CREMA_D/1001_DFA_DIS_XX.wav        6       disgust
2  audio_speech/CREMA_D/1001_DFA_FEA_XX.wav        5       fearful
3  audio_speech/CREMA_D/1001_DFA_HAP_XX.wav        2         happy
4  audio_speech/CREMA_D/1001_DFA_NEU_XX.wav        1       neutral

## Export dataset

In [11]:
df.to_csv("crema_d_labels.csv", index=False)