### Install dependencies

In [1]:
import os
import pandas as pd

### Extract components (audio speech details) from the filename

In [29]:
# Define base directory
base_dir = "audio_speech/RAVDESS"

# Go through files and extract names
data = []
file_path = []

for actor in os.listdir(base_dir): # loops through each actor's folder
    actor_path = os.path.join(base_dir, actor) # define the path name (audio_speech\Actor_01, etc)
    
    if os.path.isdir(actor_path):
        for audio_file in os.listdir(actor_path):
            if audio_file.endswith(".wav"):
                # remove the extension and split at "-" to extract each component of the name
                parts = audio_file.replace(".wav", "").split("-")
                # append to data
                data.append(parts)  
                file_path.append(base_dir + '/' + actor + '/' + audio_file)
    
file_path

['audio_speech/RAVDESS/Actor_01/03-01-01-01-01-01-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-01-01-01-02-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-01-01-02-01-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-01-01-02-02-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-02-01-01-01-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-02-01-01-02-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-02-01-02-01-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-02-01-02-02-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-02-02-01-01-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-02-02-01-02-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-02-02-02-01-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-02-02-02-02-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-03-01-01-01-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-03-01-01-02-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-03-01-02-01-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-03-01-02-02-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-03-02-01-01-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-03-02-01-02-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-03-02-02-01-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-03-02-02-02-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-04-01-01-01-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-04-01-01-02-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-04-01-02-01-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-04-01-02-02-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-04-02-01-01-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-04-02-01-02-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-04-02-02-01-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-04-02-02-02-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-05-01-01-01-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-05-01-01-02-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-05-01-02-01-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-05-01-02-02-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-05-02-01-01-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-05-02-01-02-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-05-02-02-01-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-05-02-02-02-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-06-01-01-01-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-06-01-01-02-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-06-01-02-01-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-06-01-02-02-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-06-02-01-01-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-06-02-01-02-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-06-02-02-01-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-06-02-02-02-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-07-01-01-01-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-07-01-01-02-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-07-01-02-01-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-07-01-02-02-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-07-02-01-01-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-07-02-01-02-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-07-02-02-01-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-07-02-02-02-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-08-01-01-01-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-08-01-01-02-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-08-01-02-01-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-08-01-02-02-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-08-02-01-01-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-08-02-01-02-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-08-02-02-01-01.wav',
 'audio_speech/RAVDESS/Actor_01/03-01-08-02-02-02-01.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-01-01-01-01-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-01-01-01-02-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-01-01-02-01-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-01-01-02-02-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-02-01-01-01-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-02-01-01-02-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-02-01-02-01-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-02-01-02-02-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-02-02-01-01-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-02-02-01-02-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-02-02-02-01-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-02-02-02-02-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-03-01-01-01-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-03-01-01-02-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-03-01-02-01-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-03-01-02-02-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-03-02-01-01-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-03-02-01-02-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-03-02-02-01-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-03-02-02-02-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-04-01-01-01-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-04-01-01-02-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-04-01-02-01-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-04-01-02-02-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-04-02-01-01-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-04-02-01-02-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-04-02-02-01-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-04-02-02-02-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-05-01-01-01-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-05-01-01-02-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-05-01-02-01-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-05-01-02-02-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-05-02-01-01-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-05-02-01-02-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-05-02-02-01-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-05-02-02-02-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-06-01-01-01-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-06-01-01-02-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-06-01-02-01-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-06-01-02-02-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-06-02-01-01-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-06-02-01-02-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-06-02-02-01-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-06-02-02-02-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-07-01-01-01-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-07-01-01-02-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-07-01-02-01-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-07-01-02-02-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-07-02-01-01-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-07-02-01-02-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-07-02-02-01-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-07-02-02-02-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-08-01-01-01-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-08-01-01-02-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-08-01-02-01-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-08-01-02-02-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-08-02-01-01-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-08-02-01-02-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-08-02-02-01-02.wav',
 'audio_speech/RAVDESS/Actor_02/03-01-08-02-02-02-02.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-01-01-01-01-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-01-01-01-02-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-01-01-02-01-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-01-01-02-02-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-02-01-01-01-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-02-01-01-02-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-02-01-02-01-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-02-01-02-02-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-02-02-01-01-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-02-02-01-02-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-02-02-02-01-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-02-02-02-02-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-03-01-01-01-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-03-01-01-02-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-03-01-02-01-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-03-01-02-02-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-03-02-01-01-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-03-02-01-02-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-03-02-02-01-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-03-02-02-02-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-04-01-01-01-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-04-01-01-02-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-04-01-02-01-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-04-01-02-02-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-04-02-01-01-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-04-02-01-02-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-04-02-02-01-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-04-02-02-02-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-05-01-01-01-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-05-01-01-02-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-05-01-02-01-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-05-01-02-02-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-05-02-01-01-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-05-02-01-02-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-05-02-02-01-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-05-02-02-02-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-06-01-01-01-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-06-01-01-02-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-06-01-02-01-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-06-01-02-02-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-06-02-01-01-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-06-02-01-02-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-06-02-02-01-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-06-02-02-02-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-07-01-01-01-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-07-01-01-02-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-07-01-02-01-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-07-01-02-02-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-07-02-01-01-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-07-02-01-02-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-07-02-02-01-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-07-02-02-02-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-08-01-01-01-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-08-01-01-02-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-08-01-02-01-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-08-01-02-02-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-08-02-01-01-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-08-02-01-02-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-08-02-02-01-03.wav',
 'audio_speech/RAVDESS/Actor_03/03-01-08-02-02-02-03.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-01-01-01-01-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-01-01-01-02-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-01-01-02-01-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-01-01-02-02-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-02-01-01-01-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-02-01-01-02-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-02-01-02-01-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-02-01-02-02-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-02-02-01-01-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-02-02-01-02-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-02-02-02-01-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-02-02-02-02-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-03-01-01-01-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-03-01-01-02-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-03-01-02-01-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-03-01-02-02-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-03-02-01-01-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-03-02-01-02-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-03-02-02-01-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-03-02-02-02-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-04-01-01-01-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-04-01-01-02-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-04-01-02-01-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-04-01-02-02-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-04-02-01-01-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-04-02-01-02-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-04-02-02-01-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-04-02-02-02-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-05-01-01-01-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-05-01-01-02-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-05-01-02-01-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-05-01-02-02-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-05-02-01-01-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-05-02-01-02-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-05-02-02-01-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-05-02-02-02-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-06-01-01-01-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-06-01-01-02-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-06-01-02-01-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-06-01-02-02-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-06-02-01-01-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-06-02-01-02-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-06-02-02-01-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-06-02-02-02-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-07-01-01-01-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-07-01-01-02-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-07-01-02-01-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-07-01-02-02-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-07-02-01-01-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-07-02-01-02-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-07-02-02-01-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-07-02-02-02-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-08-01-01-01-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-08-01-01-02-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-08-01-02-01-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-08-01-02-02-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-08-02-01-01-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-08-02-01-02-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-08-02-02-01-04.wav',
 'audio_speech/RAVDESS/Actor_04/03-01-08-02-02-02-04.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-01-01-01-01-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-01-01-01-02-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-01-01-02-01-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-01-01-02-02-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-02-01-01-01-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-02-01-01-02-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-02-01-02-01-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-02-01-02-02-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-02-02-01-01-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-02-02-01-02-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-02-02-02-01-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-02-02-02-02-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-03-01-01-01-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-03-01-01-02-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-03-01-02-01-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-03-01-02-02-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-03-02-01-01-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-03-02-01-02-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-03-02-02-01-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-03-02-02-02-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-04-01-01-01-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-04-01-01-02-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-04-01-02-01-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-04-01-02-02-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-04-02-01-01-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-04-02-01-02-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-04-02-02-01-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-04-02-02-02-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-05-01-01-01-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-05-01-01-02-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-05-01-02-01-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-05-01-02-02-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-05-02-01-01-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-05-02-01-02-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-05-02-02-01-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-05-02-02-02-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-06-01-01-01-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-06-01-01-02-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-06-01-02-01-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-06-01-02-02-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-06-02-01-01-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-06-02-01-02-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-06-02-02-01-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-06-02-02-02-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-07-01-01-01-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-07-01-01-02-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-07-01-02-01-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-07-01-02-02-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-07-02-01-01-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-07-02-01-02-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-07-02-02-01-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-07-02-02-02-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-08-01-01-01-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-08-01-01-02-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-08-01-02-01-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-08-01-02-02-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-08-02-01-01-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-08-02-01-02-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-08-02-02-01-05.wav',
 'audio_speech/RAVDESS/Actor_05/03-01-08-02-02-02-05.wav',
 'audio_speech/RAVDESS/Actor_06/03-01-01-01-01-01-06.wav',
 'audio_speech/RAVDESS/Actor_06/03-01-01-01-01-02-06.wav',
 'audio_speech/RAVDESS/Actor_06/03-01-01-01-02-01-06.wav',
 'audio_speech/RAVDESS/Actor_06/03-01-01-01-02-02-06.wav',
 'audio_speech/RAVDESS/Actor_06/03-01-02-01-01-01-06.wav',
 'audio_speech/RAVDESS/Actor_06/03-01-02-01-01-02-06.wav',
 'audio_speech/RAVDESS/Actor_06/03-01-02-01-02-01-06.wav',
 'audio_speech/RAVDESS/Actor_06/03-01-02-01-02-02-06.wav',
 'audio_speech/RAVDESS/Actor_06/03-01-02-02-01-01-06.wav',
 'audio_speech/RAVDESS/Actor_06/03-01-02-02-01-02-06.wav',
 'audio_speech/RAVDESS/Actor_06/03-01-02-02-02-01-06.wav',
 'audio_speech/RAVDESS/Actor_06/03-01-02-02-02-02-06.wav',
 'audio_speech/RAVDESS/Actor_06/03-01-03-01-01-01-06.wav',
 'audio_speech/RAVDESS/Actor_06/03-01-03-01-01-02-06.wav',
 'audio_speech/RAVDESS/Actor_06/03-01-03-01-02-01-06.wav',
 'audio_speech/RAVDESS/Actor_06/03-01-03-01-02-02-06.wav',
 'audio_speech/RAVDESS/Actor_06/03-01-03-02-01-01-06.wav',
 'audio_speech/RAVDESS/Actor_06/03-01-03-02-01-02-06.wav',
 'audio_speech/RAVDESS/Actor_06/03-01-03-02-02-01-06.wav',
 'audio_speech/RAVDESS/Actor_06/03-01-03-02-02-02-06.wav',
 'audio_speech/RAVDESS/Actor_06/03-01-04-01-01-01-06.wav',
 'audio_speech/RAVDESS/Actor_06/03-01-04-01-01-02-06.wav',
 'audio_speech/RAVDESS/Actor_06/03-01-04-01-02-01-06.wav',
 'audio_speech/RAVDESS/Actor_06/03-01-04-01-02-02-06.wav',
 'audio_speech/RAVDESS/Actor_06/03-01-04-02-01-01-06.wav',
 'audio_speech/RAVDESS/Actor_06/03-01-04-02-01-02-06.wav',
 'audio_speech/RAVDESS/Actor_06/03-01-04-02-02-01-06.wav',
 'audio_speech/RAVDESS/Actor_06/03-01-04-02-02-02-06.wav',
 'audio_speech/RAVDESS/Actor_06/03-01-05-01-01-01-06.wav',
 'audio_speech/RAVDESS/Actor_06/03-01-05-01-01-02-06.wav',
 'audio_speech/RAVDESS/Actor_06/03-01-05-01-02-01-06.wav',
 'audio_speech/RAVDESS/Actor_06/03-01-05-01-02-02-06.wav',
 'audio_speech/RAVDESS/Actor_06/03-01-05-02-01-01-06.wav',
 'audio_speech/RAVDESS/Actor_06/03-01-05-02-01-02-06.wav',
 'audio_speech/RAVDESS/Actor_06/03-01-05-02-02-01-06.wav',
 'audio_speech/RAVDESS/Actor_06/03-01-05-02-02-02-06.wav',
 'audio_speech/RAVDESS/Actor_06/03-01-06-01-01-01-06.wav',
 'audio_speech/RAVDESS/Actor_06/03-01-06-01-01-02-06.wav',

### Convert the data extracted to a dataframe

In [30]:
# Define column names
columns = [
    "Modality",
    "Vocal_channel",
    "Emotion",
    "Emotional_intensity",
    "Statement",
    "Repetition",
    "Actor"
]

# Create dataframe
df = pd.DataFrame(data, columns=columns)
df = df.astype(int)
df.insert(0, "file_path", file_path)
df.head(10)

,file_path,Modality,Vocal_channel,Emotion,Emotional_intensity,Statement,Repetition,Actor
0,audio_speech/RAVDESS/Actor_01/03-01-01-01-01-0...,3,1,1,1,1,1,1
1,audio_speech/RAVDESS/Actor_01/03-01-01-01-01-0...,3,1,1,1,1,2,1
2,audio_speech/RAVDESS/Actor_01/03-01-01-01-02-0...,3,1,1,1,2,1,1
3,audio_speech/RAVDESS/Actor_01/03-01-01-01-02-0...,3,1,1,1,2,2,1
4,audio_speech/RAVDESS/Actor_01/03-01-02-01-01-0...,3,1,2,1,1,1,1
5,audio_speech/RAVDESS/Actor_01/03-01-02-01-01-0...,3,1,2,1,1,2,1
6,audio_speech/RAVDESS/Actor_01/03-01-02-01-02-0...,3,1,2,1,2,1,1
7,audio_speech/RAVDESS/Actor_01/03-01-02-01-02-0...,3,1,2,1,2,2,1
8,audio_speech/RAVDESS/Actor_01/03-01-02-02-01-0...,3,1,2,2,1,1,1
9,audio_speech/RAVDESS/Actor_01/03-01-02-02-01-0...,3,1,2,2,1,2,1

In [31]:
# Combine neutral and calm emotions, then align the emotions by making them from 1-7 instead of 1-8
df.Emotion.replace({1:1, 2:1, 3:2, 4:3, 5:4, 6:5, 7:6, 8:7}, inplace=True)

C:\Users\AowenC\AppData\Local\Temp\ipykernel_23288\2570194178.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Emotion.replace({1:1, 2:1, 3:2, 4:3, 5:4, 6:5, 7:6, 8:7}, inplace=True)

### EDA

In [9]:
df.Emotion.value_counts()

Emotion
1    288
2    192
3    192
4    192
5    192
6    192
7    192
Name: count, dtype: int64

In [10]:
# Looking at Actor 1 recordings
df[df["Actor"] == 1]

,file_path,Modality,Vocal_channel,Emotion,Emotional_intensity,Statement,Repetition,Actor
0,audio_speech/RAVDESS_03-01-01-01-01-01-01.wav,3,1,1,1,1,1,1
1,audio_speech/RAVDESS_03-01-01-01-01-02-01.wav,3,1,1,1,1,2,1
2,audio_speech/RAVDESS_03-01-01-01-02-01-01.wav,3,1,1,1,2,1,1
3,audio_speech/RAVDESS_03-01-01-01-02-02-01.wav,3,1,1,1,2,2,1
4,audio_speech/RAVDESS_03-01-02-01-01-01-01.wav,3,1,1,1,1,1,1
5,audio_speech/RAVDESS_03-01-02-01-01-02-01.wav,3,1,1,1,1,2,1
6,audio_speech/RAVDESS_03-01-02-01-02-01-01.wav,3,1,1,1,2,1,1
7,audio_speech/RAVDESS_03-01-02-01-02-02-01.wav,3,1,1,1,2,2,1
8,audio_speech/RAVDESS_03-01-02-02-01-01-01.wav,3,1,1,2,1,1,1
9,audio_speech/RAVDESS_03-01-02-02-01-02-01.wav,3,1,1,2,1,2,1
10,audio_speech/RAVDESS_03-01-02-02-02-01-01.wav,3,1,1,2,2,1,1
11,audio_speech/RAVDESS_03-01-02-02-02-02-01.wav,3,1,1,2,2,2,1
12,audio_speech/RAVDESS_03-01-03-01-01-01-01.wav,3,1,2,1,1,1,1
13,audio_speech/RAVDESS_03-01-03-01-01-02-01.wav,3,1,2,1,1,2,1
14,audio_speech/RAVDESS_03-01-03-01-02-01-01.wav,3,1,2,1,2,1,1
15,audio_speech/RAVDESS_03-01-03-01-02-02-01.wav,3,1,2,1,2,2,1
16,audio_speech/RAVDESS_03-01-03-02-01-01-01.wav,3,1,2,2,1,1,1
17,audio_speech/RAVDESS_03-01-03-02-01-02-01.wav,3,1,2,2,1,2,1
18,audio_speech/RAVDESS_03-01-03-02-02-01-01.wav,3,1,2,2,2,1,1
19,audio_speech/RAVDESS_03-01-03-02-02-02-01.wav,3,1,2,2,2,2,1
20,audio_speech/RAVDESS_03-01-04-01-01-01-01.wav,3,1,3,1,1,1,1
21,audio_speech/RAVDESS_03-01-04-01-01-02-01.wav,3,1,3,1,1,2,1
22,audio_speech/RAVDESS_03-01-04-01-02-01-01.wav,3,1,3,1,2,1,1
23,audio_speech/RAVDESS_03-01-04-01-02-02-01.wav,3,1,3,1,2,2,1
24,audio_speech/RAVDESS_03-01-04-02-01-01-01.wav,3,1,3,2,1,1,1
25,audio_speech/RAVDESS_03-01-04-02-01-02-01.wav,3,1,3,2,1,2,1
26,audio_speech/RAVDESS_03-01-04-02-02-01-01.wav,3,1,3,2,2,1,1
27,audio_speech/RAVDESS_03-01-04-02-02-02-01.wav,3,1,3,2,2,2,1
28,audio_speech/RAVDESS_03-01-05-01-01-01-01.wav,3,1,4,1,1,1,1
29,audio_speech/RAVDESS_03-01-05-01-01-02-01.wav,3,1,4,1,1,2,1
30,audio_speech/RAVDESS_03-01-05-01-02-01-01.wav,3,1,4,1,2,1,1
31,audio_speech/RAVDESS_03-01-05-01-02-02-01.wav,3,1,4,1,2,2,1
32,audio_speech/RAVDESS_03-01-05-02-01-01-01.wav,3,1,4,2,1,1,1
33,audio_speech/RAVDESS_03-01-05-02-01-02-01.wav,3,1,4,2,1,2,1
34,audio_speech/RAVDESS_03-01-05-02-02-01-01.wav,3,1,4,2,2,1,1
35,audio_speech/RAVDESS_03-01-05-02-02-02-01.wav,3,1,4,2,2,2,1
36,audio_speech/RAVDESS_03-01-06-01-01-01-01.wav,3,1,5,1,1,1,1
37,audio_speech/RAVDESS_03-01-06-01-01-02-01.wav,3,1,5,1,1,2,1
38,audio_speech/RAVDESS_03-01-06-01-02-01-01.wav,3,1,5,1,2,1,1
39,audio_speech/RAVDESS_03-01-06-01-02-02-01.wav,3,1,5,1,2,2,1
40,audio_speech/RAVDESS_03-01-06-02-01-01-01.wav,3,1,5,2,1,1,1
41,audio_speech/RAVDESS_03-01-06-02-01-02-01.wav,3,1,5,2,1,2,1
42,audio_speech/RAVDESS_03-01-06-02-02-01-01.wav,3,1,5,2,2,1,1
43,audio_speech/RAVDESS_03-01-06-02-02-02-01.wav,3,1,5,2,2,2,1
44,audio_speech/RAVDESS_03-01-07-01-01-01-01.wav,3,1,6,1,1,1,1
45,audio_speech/RAVDESS_03-01-07-01-01-02-01.wav,3,1,6,1,1,2,1
46,audio_speech/RAVDESS_03-01-07-01-02-01-01.wav,3,1,6,1,2,1,1
47,audio_speech/RAVDESS_03-01-07-01-02-02-01.wav,3,1,6,1,2,2,1
48,audio_speech/RAVDESS_03-01-07-02-01-01-01.wav,3,1,6,2,1,1,1
49,audio_speech/RAVDESS_03-01-07-02-01-02-01.wav,3,1,6,2,1,2,1
50,audio_speech/RAVDESS_03-01-07-02-02-01-01.wav,3,1,6,2,2,1,1
51,audio_speech/RAVDESS_03-01-07-02-02-02-01.wav,3,1,6,2,2,2,1
52,audio_speech/RAVDESS_03-01-08-01-01-01-01.wav,3,1,7,1,1,1,1
53,audio_speech/RAVDESS_03-01-08-01-01-02-01.wav,3,1,7,1,1,2,1
54,audio_speech/RAVDESS_03-01-08-01-02-01-01.wav,3,1,7,1,2,1,1
55,audio_speech/RAVDESS_03-01-08-01-02-02-01.wav,3,1,7,1,2,2,1
56,audio_speech/RAVDESS_03-01-08-02-01-01-01.wav,3,1,7,2,1,1,1
57,audio_speech/RAVDESS_03-01-08-02-01-02-01.wav,3,1,7,2,1,2,1
58,audio_speech/RAVDESS_03-01-08-02-02-01-01.wav,3,1,7,2,2,1,1
59,audio_speech/RAVDESS_03-01-08-02-02-02-01.wav,3,1,7,2,2,2,1

In [11]:
# Checking number of audio recordings per Actor
df.groupby("Actor").count()

# Looks like no missing recordings (based on file count alone)

,file_path,Modality,Vocal_channel,Emotion,Emotional_intensity,Statement,Repetition
Actor,,,,,,,
1,60,60,60,60,60,60,60
2,60,60,60,60,60,60,60
3,60,60,60,60,60,60,60
4,60,60,60,60,60,60,60
5,60,60,60,60,60,60,60
6,60,60,60,60,60,60,60
7,60,60,60,60,60,60,60
8,60,60,60,60,60,60,60
9,60,60,60,60,60,60,60
10,60,60,60,60,60,60,60
11,60,60,60,60,60,60,60
12,60,60,60,60,60,60,60
13,60,60,60,60,60,60,60
14,60,60,60,60,60,60,60
15,60,60,60,60,60,60,60
16,60,60,60,60,60,60,60
17,60,60,60,60,60,60,60
18,60,60,60,60,60,60,60
19,60,60,60,60,60,60,60
20,60,60,60,60,60,60,60
21,60,60,60,60,60,60,60
22,60,60,60,60,60,60,60
23,60,60,60,60,60,60,60
24,60,60,60,60,60,60,60

In [12]:
# Ensure it is all audio
df.groupby("Actor")["Modality"].unique()

Actor
1     [3]
2     [3]
3     [3]
4     [3]
5     [3]
6     [3]
7     [3]
8     [3]
9     [3]
10    [3]
11    [3]
12    [3]
13    [3]
14    [3]
15    [3]
16    [3]
17    [3]
18    [3]
19    [3]
20    [3]
21    [3]
22    [3]
23    [3]
24    [3]
Name: Modality, dtype: object

In [13]:
# Ensure it is all speech
df.groupby("Actor")["Vocal_channel"].unique()

Actor
1     [1]
2     [1]
3     [1]
4     [1]
5     [1]
6     [1]
7     [1]
8     [1]
9     [1]
10    [1]
11    [1]
12    [1]
13    [1]
14    [1]
15    [1]
16    [1]
17    [1]
18    [1]
19    [1]
20    [1]
21    [1]
22    [1]
23    [1]
24    [1]
Name: Vocal_channel, dtype: object

### Adding human readable tags

In [32]:
emotion_map = {
    1: "neutral",
    2: "happy",
    3: "sad",
    4: "angry",
    5: "fearful",
    6: "disgust",
    7: "surprised"
}

intensity_map = {1: "normal", 2: "strong"}
statement_map = {1: "Kids are talking by the door", 2: "Dogs are sitting by the door"}

df["Emotion_label"] = df["Emotion"].map(emotion_map)
df["Intensity_label"] = df["Emotional_intensity"].map(intensity_map)
df["Statement_label"] = df["Statement"].map(statement_map)
df["Actor_gender"] = df["Actor"].apply(lambda x: "male" if x % 2 else "female")

df.head()

,file_path,Modality,Vocal_channel,Emotion,Emotional_intensity,Statement,Repetition,Actor,Emotion_label,Intensity_label,Statement_label,Actor_gender
0,audio_speech/RAVDESS/Actor_01/03-01-01-01-01-0...,3,1,1,1,1,1,1,neutral,normal,Kids are talking by the door,male
1,audio_speech/RAVDESS/Actor_01/03-01-01-01-01-0...,3,1,1,1,1,2,1,neutral,normal,Kids are talking by the door,male
2,audio_speech/RAVDESS/Actor_01/03-01-01-01-02-0...,3,1,1,1,2,1,1,neutral,normal,Dogs are sitting by the door,male
3,audio_speech/RAVDESS/Actor_01/03-01-01-01-02-0...,3,1,1,1,2,2,1,neutral,normal,Dogs are sitting by the door,male
4,audio_speech/RAVDESS/Actor_01/03-01-02-01-01-0...,3,1,1,1,1,1,1,neutral,normal,Kids are talking by the door,male

In [33]:
df.Emotion_label.value_counts()

Emotion_label
neutral      288
happy        192
sad          192
angry        192
fearful      192
disgust      192
surprised    192
Name: count, dtype: int64

In [22]:
df.head()

,file_path,Modality,Vocal_channel,Emotion,Emotional_intensity,Statement,Repetition,Actor,Emotion_label,Intensity_label,Statement_label,Actor_gender
0,audio_speech/RAVDESS/03-01-01-01-01-01-01.wav,3,1,1,1,1,1,1,neutral,normal,Kids are talking by the door,male
1,audio_speech/RAVDESS/03-01-01-01-01-02-01.wav,3,1,1,1,1,2,1,neutral,normal,Kids are talking by the door,male
2,audio_speech/RAVDESS/03-01-01-01-02-01-01.wav,3,1,1,1,2,1,1,neutral,normal,Dogs are sitting by the door,male
3,audio_speech/RAVDESS/03-01-01-01-02-02-01.wav,3,1,1,1,2,2,1,neutral,normal,Dogs are sitting by the door,male
4,audio_speech/RAVDESS/03-01-02-01-01-01-01.wav,3,1,1,1,1,1,1,neutral,normal,Kids are talking by the door,male

### Export file as csv

In [34]:
df.to_csv("ravdess_labels.csv", index=False)