In [1]:
import os
import pandas as pd

In [14]:
TESS_BASE_DIR = "audio_speech/TESS/"

In [49]:
tess_directory_list = os.listdir(TESS_BASE_DIR)

file_emotion = []
file_path = []

for dir in tess_directory_list:
    for file in os.listdir(TESS_BASE_DIR + dir): # returns a list of all the file/audio names in each directory
        # Extract emotion
        emotion = file.split('.')[0]    # i.e. ['OAF_back_angry', 'wav'], pos 0 gets what we want
        emotion = emotion.split('_')[2] # i.e. ['OAF', 'back', 'angry'], pos 2 gets what we want

        # To match the ravdess encodings
        if emotion == 'neutral':
            file_emotion.append(1)
        elif emotion == 'happy':
            file_emotion.append(2)
        elif emotion == 'sad':
            file_emotion.append(3)
        elif emotion == 'angry':
            file_emotion.append(4)
        elif emotion == 'fear':
            file_emotion.append(5)
        elif emotion == 'disgust':
            file_emotion.append(6)
        elif emotion == 'ps':
            file_emotion.append(7)
        else:
            file_emotion.append(0)

        # Get path of each audio file
        file_path.append(TESS_BASE_DIR + dir + '/' + file)

In [50]:
df = pd.DataFrame(list(zip(file_path, file_emotion)), columns=['file_path', 'Emotion'])
df.head()

                                        file_path  Emotion
0  audio_speech/TESS/OAF_angry/OAF_back_angry.wav        4
1   audio_speech/TESS/OAF_angry/OAF_bar_angry.wav        4
2  audio_speech/TESS/OAF_angry/OAF_base_angry.wav        4
3  audio_speech/TESS/OAF_angry/OAF_bath_angry.wav        4
4  audio_speech/TESS/OAF_angry/OAF_bean_angry.wav        4

In [51]:
# Add human readable labels to the emotions
emotion_map = {
    1: "neutral",
    2: "happy",
    3: "sad",
    4: "angry",
    5: "fearful",
    6: "disgust",
    7: "surprised"
}

df["Emotion_label"] = df["Emotion"].map(emotion_map)

In [53]:
df.Emotion_label.value_counts().sort_index()

Emotion_label
angry        400
disgust      400
fearful      400
happy        400
neutral      400
sad          400
surprised    400
Name: count, dtype: int64

In [54]:
df.head()

                                        file_path  Emotion Emotion_label
0  audio_speech/TESS/OAF_angry/OAF_back_angry.wav        4         angry
1   audio_speech/TESS/OAF_angry/OAF_bar_angry.wav        4         angry
2  audio_speech/TESS/OAF_angry/OAF_base_angry.wav        4         angry
3  audio_speech/TESS/OAF_angry/OAF_bath_angry.wav        4         angry
4  audio_speech/TESS/OAF_angry/OAF_bean_angry.wav        4         angry

## Export dataset

In [55]:
df.to_csv("tess_labels.csv", index=False)

: